### ISSUE TITLE
Practica(DIAGRAMA DE CLASES)

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-equipo_-campo#2]
[practica diagrama.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-equipo_-campo/files/14727476/practica.diagrama.pdf)

**Comment by lucero012** [comment]
Portada: 25
Procedimiento : 25
Figuras, ilustraciones y fotografías.: 25
Resultados y conclusiones: 25
calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
